# Generated by Django 4.1.3 on 2022-11-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=244)),
                ('password', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
