# Generated by Django 4.1.3 on 2022-11-20 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('first_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_first_peron', to='chat.user')),
                ('second_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_second_person', to='chat.user')),
            ],
        ),
    ]
