# Generated by Django 4.1.3 on 2022-11-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_thread'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together={('first_person', 'second_person')},
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_time', models.DateField(auto_now_add=True)),
                ('send_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.user')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.thread')),
            ],
        ),
    ]
