# Generated by Django 4.1.3 on 2023-01-31 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_thread_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together={('first_person', 'second_person')},
        ),
    ]
