# Generated by Django 4.1.3 on 2023-02-07 14:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_workspace_workspacemembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelName', models.CharField(max_length=100)),
                ('DateCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.workspace')),
            ],
        ),
    ]
