# Generated by Django 4.1.3 on 2023-02-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_channelmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChannelMessage',
        ),
    ]
