# Generated by Django 4.1.3 on 2023-02-08 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_channelmessage_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_channel', to='chat.channel'),
        ),
    ]
