# Generated by Django 4.1.3 on 2023-02-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_channelmessage_channel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='thread',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.workspace'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='first_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_first_person', to='chat.user'),
        ),
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together={('first_person', 'second_person', 'workspace')},
        ),
    ]
