# Generated by Django 4.1.3 on 2023-02-09 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_thread_unique_together_thread_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.workspace'),
        ),
    ]
