# Generated by Django 4.1.3 on 2023-02-12 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_thread_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_by', to='chat.user')),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_to', to='chat.user')),
                ('worksapce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.workspace')),
            ],
        ),
    ]
