# Generated by Django 4.1.3 on 2023-02-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='worksapce',
            new_name='workspace',
        ),
    ]
