# Generated by Django 4.1.3 on 2023-02-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_rename_worksapce_invitation_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
