# Generated by Django 4.1.7 on 2023-04-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_user_forget_pass_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='file',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='has_file',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='is_image',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='has_file',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_image',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
