# Generated by Django 4.1.7 on 2023-04-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_channelmessage_file_channelmessage_has_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmessage',
            name='is_image',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_image',
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='file_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
