# Generated by Django 4.1.7 on 2023-04-06 11:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_remove_channelmessage_is_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenByChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.channelmessage')),
                ('seen_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.user')),
            ],
        ),
    ]
