# Generated by Django 4.1.7 on 2023-04-06 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_seenbychannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='seenbychannel',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.channel'),
        ),
    ]
