# Generated by Django 4.1.7 on 2023-04-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_seenbychannel_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seenbychannel',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_seen_by', to='chat.channelmessage'),
        ),
    ]
